[
  ./config/defaults/default.nix
  ./config/defaults/environment.nix
  ./config/defaults/networking.nix
  ./config/defaults/nginx.nix
  ./config/defaults/nix.nix
  ./config/defaults/security.nix
  ./config/defaults/ssh.nix
  ./config/defaults/sudo.nix
  ./config/defaults/system.nix
  ./config/defaults/users.nix
  ./config/services/fail2ban.nix
  ./config/hardware/mbr.nix
  ./config/hardware/uefi.nix
  ./config/overlays.nix
  ./core/keychain
  ./core/module-hashes.nix
  ./dns/unbound-adblock
  ./networking/pcap-prep
  ./networking/ndppd
  ./services/full-tunnel-vpn
  ./services/hydra-manual-setup
  ./services/systemd-digitalocean
  ./services/netsniff-ng
  ./services/znc
]
