[
  ./config/defaults/default.nix
  ./config/defaults/environment.nix
  ./config/defaults/networking.nix
  ./config/defaults/nginx.nix
  ./config/defaults/nix.nix
  ./config/defaults/security.nix
  ./config/defaults/ssh.nix
  ./config/defaults/sudo.nix
  ./config/defaults/system.nix
  ./config/defaults/users.nix
  ./config/hardware/mbr.nix
  ./config/hardware/uefi.nix
  ./core/module-hashes.nix
  ./networking/pcap-prep
  ./services/hydra-manual-setup
  ./services/netsniff-ng
  ./services/znc
]
