[
  ./config/defaults/environment.nix
  ./config/defaults/networking.nix
  ./config/defaults/nix.nix
  ./config/defaults/security.nix
  ./config/defaults/sudo.nix
  ./config/defaults/system.nix
  ./config/defaults/users.nix
]
