{ lib, pkgs }:

with lib;

{
  enable = mkEnableOption "Enable a full-tunnel StrongSwan VPN server.";

  remoteId = mkOption {
    type = types.string;
    example = "vpn.example.org";
    description = ''
      The remote ID used by clients to describe the server
      ("Remote ID" string, in macOS and iOS). This should
      probably be the server's FQDN.
    '';
  };

  dns = mkOption {
    type = types.listOf (types.either pkgs.lib.types.ipv4NoCidr pkgs.lib.types.ipv6NoCidr);
    default = [ "8.8.8.8" "2001:4860:4860::8844" ];
    description = ''
      DNS servers to be pushed to StrongSwan clients.
    '';
  };

  ipv4ClientCidr = mkOption {
    type = pkgs.lib.types.ipv4Cidr;
    example = "10.0.1.0/24";
    description = ''
      The base of the IPv4 address range that will be used for
      StrongSwan clients, in CIDR format.
    '';
  };

  ipv6ClientPrefix = mkOption {
    type = pkgs.lib.types.ipv6Cidr;
    example = "2001:DB8::1:0/112";
    description = ''
      The IPv6 prefix from which IPv6 addresses will be assigned
      for StrongSwan clients.
    '';
  };

  caFile = mkOption {
    type = types.path;
    description = ''
      A path to the CA certificate used to authenticate client
      certificates for the StrongSwan server.
    '';
  };

  certFile = mkOption {
    type = types.path;
    description = ''
      A path to the StrongSwan server's public certificate.
    '';
  };

  certKeyFile = mkOption {
    type = types.path;
    example = "/run/keys/strongswan-cert";
    description = ''
      A path to the server's private key. Note that this file will not
      be copied to the Nix store; the StrongSwan server will expect
      the file to be at the given path when it starts, so it must be
      deployed to the host out-of-band.

      If you use NixOps and you deploy the key using NixOps's
      <option>deployment.keys</option> option, the StrongSwan server
      will automatically wait for that key to be present before it
      runs.

      Upon start-up, the service will copy the key to its persistent
      state directory.
    '';
  };

  crlFile = mkOption {
    type = types.path;
    description = ''
      A path to the CA's CRL file, for revoked certs.
    '';
  };

  description = ''
    A declarative StrongSwan IKEv2 "full-tunnel" server.

    IPv4 traffic that is routed to a full-tunnel StrongSwan server
    will be NATed to the server's public IPv4 address. IPv6 traffic
    will be routed normally and clients will be given a public IPv6
    address from the pool assigned to the StrongSwan server.

    This server is configured to listen on the standard IKEv2 UDP
    ports 500 and 4500.
    
    Note that the configuration generated by this module has only been
    tested with iOS and macOS devices.
  '';
}
